#!/usr/bin/env python3
"""
Generate OCaml bindings for CakeML API insulation.

This script reads a types.txt file from CakeML and generates OCaml code that:
1. Creates a Cake module with all CakeML functions properly namespaced
2. Binds original module names to empty modules to force usage through Cake
"""

import sys
from collections import defaultdict
from pathlib import Path

# Compatibility layer
MODULE_RENAMES = {
    'TextIO': 'Text_io',
    'Word8Array': 'Word8_array',
    'CommandLine': 'Command_line',
    'PrettyPrinter': 'Pretty_printer'
}

# Ignore any bindings that contain any of the following strings
IGNORED_BINDINGS = {
    'TextIO',  # shadowing this will break the REPL in strange ways
    'PrettyPrinter',  # shadowing this might break the REPL in strange ways
    'assert',  # parser issue
    '~',  # parser issue
}

# Identifiers that are not symbols but still need to be parenthesized
INFIX_NAMES = {
    "mod"
}

# types.txt does not contain types, but we need to rebind them so the
# pretty-printers get generated.
# Note that if the module does not exist in types.txt this part gets ignored.
#
# Entries are of the form (type_var list, type_name).
MODULE_TYPES = {
    'Rat': [([], 'rat')],
    'Double': [([], 'double')],
    'Hashtable': [(['a', 'b'], 'hashtable')]
}


def format_type_entry(entry):
    """
    Parse a MODULE_TYPES entry and return (type_params_str, type_name).

    type_params_str is the OCaml type parameter prefix (e.g. "'a " or "('a, 'b) "
    or "" for no parameters).
    """
    type_vars, type_name = entry

    if not type_vars:
        return '', type_name

    quoted = [f"'{v}" for v in type_vars]
    if len(quoted) == 1:
        return f"{quoted[0]} ", type_name
    else:
        return f"({', '.join(quoted)}) ", type_name


def handle_func_name(name):
    """
    Parenthesizes + renames OCaml identifiers as necessary.

    Examples:
      'delete' -> 'delete'
      '*' -> '( * )'
      '+' -> '(+)'
    """
    if all(c.isalnum() or c in '_\'' for c in name) and not name in INFIX_NAMES:
        return name
    elif name.startswith("*"):  # Special case to avoid (* comment syntax
        return f'( {name} )'
    else:
        return f'({name})'


def count_parameters(type_sig):
    """
    Count the number of parameters in a function type signature.
    Only counts top-level arrows, not arrows inside parentheses.

    Examples:
      'unit -> unit' : 1
      'a -> b -> c' : 2
      '(a -> b) -> c' : 1 (arrow inside parens doesn't count)
    """
    depth = 0
    arrow_count = 0
    i = 0

    while i < len(type_sig):
        char = type_sig[i]

        if char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
        elif char == '-' and depth == 0:
            # Check if this is part of '->'
            if i + 1 < len(type_sig) and type_sig[i + 1] == '>':
                arrow_count += 1
                i += 1  # Skip the '>'

        i += 1

    return arrow_count


def parse_types_file(content):
    """Parse types.txt and extract module.function mappings."""
    bindings = defaultdict(list)

    for line in content.splitlines():
        # Skip empty lines
        if not line.strip():
            continue

        parts = line.split(': ', 1)
        name_part, type_part = parts[0].strip(), parts[1].strip()

        # Skip ignored bindings
        if any(ignore in name_part for ignore in IGNORED_BINDINGS):
            continue

        parts = name_part.split('.')
        if len(parts) != 2:  # Skip top-level and nested modules
            continue
        module_name, func_name = parts

        bindings[MODULE_RENAMES.get(module_name, module_name)].append({
            'func_name': handle_func_name(func_name),
            'param_count': count_parameters(type_part),
        })

    return bindings


def generate_ocaml_bindings(bindings):
    """Generate OCaml code for the Cake module and empty module stubs."""
    lines = []

    # Generate the Cake module
    lines.append("(* Generated by candle_insulate.py based on CakeML's types.txt *)")
    lines.append("(* This file insulates the codebase from direct CakeML API usage *)")
    lines.append("")
    lines.append("module Cake = struct")

    # Get all module names (sorted for consistent output)
    module_names = sorted([m for m in bindings.keys() if m])

    # Generate submodules within Cake
    for module_name in module_names:
        lines.append(f"  module {module_name} = struct")

        # Add type rebindings if specified for this module
        if module_name in MODULE_TYPES:
            for entry in MODULE_TYPES[module_name]:
                params_str, type_name = format_type_entry(entry)
                lines.append(f"    type {params_str}{type_name} = {params_str}{module_name}.{type_name}")
            lines.append("")

        # Add all functions for this module with eta expansion and symbol escaping
        for binding_info in sorted(bindings[module_name], key=lambda x: x['func_name']):
            func_name = binding_info['func_name']
            param_count = binding_info['param_count']

            # Try to do as much eta-expansion as possible for performance reasons (2026-02-06)
            if param_count == 0:
                lines.append(f"    let {func_name} = {module_name}.{func_name}")
            else:
                params = ' '.join(f'x{i}' for i in range(param_count))
                lines.append(f"    let {func_name} {params} = {module_name}.{func_name} {params}")

        lines.append("  end;;")
        lines.append("")

    lines.append("end;;")
    lines.append("")

    # Generate module stubs that re-export pretty printers
    lines.append("(* Module stubs to prevent direct CakeML API usage *)")
    lines.append("(* Users must access these through the Cake module *)")
    lines.append("(* Types are re-exported so that pretty printers still work *)")
    lines.append("")

    for ocaml_module_name in module_names:
        if ocaml_module_name in MODULE_TYPES:
            lines.append(f"module {ocaml_module_name} = struct")
            for entry in MODULE_TYPES[ocaml_module_name]:
                params_str, type_name = format_type_entry(entry)
                lines.append(f"  type {params_str}{type_name} = {params_str}Cake.{ocaml_module_name}.{type_name}")
            lines.append("end;;")
        else:
            lines.append(f"module {ocaml_module_name} = struct end;;")

    lines.append("")
    lines.append("(* End of generated section *)")


    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_cake_bindings.py <types.txt> [output.ml]")
        print("  If output file is not specified, prints to stdout")
        sys.exit(1)

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else None

    if not input_file.exists():
        print(f"Error: Input file '{input_file}' not found")
        sys.exit(1)

    # Read and parse the types file
    content = input_file.read_text()
    bindings = parse_types_file(content)
    ocaml_code = generate_ocaml_bindings(bindings)

    # Output
    if output_file:
        output_file.write_text(ocaml_code)
        print(f"Generated bindings written to {output_file}")
    else:
        print(ocaml_code)


if __name__ == '__main__':
    main()
