"""Generate repeated agent context and the plan template from the authority lock."""
from pathlib import Path
import argparse
import json
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "infra"))
from agentinfra.contracts import authority, authority_digest


def artifacts():
    source = authority()
    outputs = {}
    # Include new source files too; no runtime/build/vendor enumeration.
    paths = subprocess.check_output(["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"], cwd=ROOT).decode().split("\0")
    dirs = {Path("docs/generated"), Path("templates")}
    for name in paths:
        if not name or not (ROOT / name).is_file() or name.startswith((".aegis/", ".candle/evidence/")):
            continue
        dirs.update(p for p in Path(name).parents if str(p) != ".")
    for directory in dirs:
        up = "../" * len(directory.parts)
        outputs[(directory / "AGENTS.md").as_posix()] = (
            "<!-- Generated by scripts/generate.py; edit root AGENTS.md. -->\n"
            "# Candle-rs instructions\n\n"
            f"Read [{up}AGENTS.md]({up}AGENTS.md) and [{up}INDEX.md]({up}INDEX.md).\n"
            "Original Candle HOL4 specifications are the shared contract; the ITP 2022 paper\n"
            "is the ultimate scientific reference. Preserve original syntax and semantics.\n"
            "Implement in Rust; use Kani/Verus with honest assumptions and scoped claims.\n"
            "Reuse first, generate second, justify handwritten code. No test-order, style,\n"
            "performance, concurrency or output-speed mandates. Request GPT 6 Astra.\n"
            "Keep supervision records and publish small stacked PRs before the next cycle.\n"
        )
    template = {
        "schema": 1, "task": "kernel-typeof", "authority_sha256": authority_digest(),
        "paper_sections": ["3.1", "3.3"],
        "reuse": {"strategy": "generate", "sources": ["pinned CakeML/cakeml original theory", "Kani proof harness pattern"],
                  "license": "REPLACE: inspect source licenses before copying", "reason": "REPLACE: record evaluated reuse alternatives",
                  "generator": ["python3", "tools/generate_kernel_obligations.py"]},
        "adr": "docs/adr/0001-kernel-refinement.md", "remote": {"repository": "QuasarRay/Candle-rs", "base": "main"},
        "obligations": [{"id": "kernel-typeof", "anchor": "candle/standard/syntax/holSyntaxScript.sml",
                         "symbol": "typeof_def", "statement": "REPLACE: exact Rust/HOL4 representation relation and domain",
                         "rust_paths": ["src/kernel.rs", "src/proofs.rs"], "method": "kani", "entry": "proofs::kernel_typeof",
                         "expected_checks": 1, "assumptions": ["REPLACE: list trusted correspondence and environment assumptions"],
                         "limits": ["REPLACE: bounded term depth, allocation, unwind and input domain"]}]
    }
    outputs["templates/candle-plan.json"] = json.dumps(template, indent=2) + "\n"
    lines = ["# Original specification anchors", "", "Generated from `contracts/authority.json`; not a completeness or proof claim.", "",
             "| Original path | SHA-256 |", "| --- | --- |"]
    lines += [f"| `{s['path']}` | `{s['sha256']}` |" for s in source["specifications"]]
    outputs["docs/generated/anchors.md"] = "\n".join(lines) + "\n"
    # Include instruction files for directories that the generated outputs introduce.
    for directory in (Path("docs/generated"), Path("templates")):
        up = "../" * len(directory.parts)
        outputs.setdefault(str(directory / "AGENTS.md"), f"<!-- Generated by scripts/generate.py; edit root AGENTS.md. -->\n# Candle-rs instructions\n\nRead [{up}AGENTS.md]({up}AGENTS.md); all root instructions apply.\n")
    return outputs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []
    for name, content in sorted(artifacts().items()):
        p = ROOT / name
        if p.exists() and p.read_text() == content:
            continue
        changed.append(name)
        if not args.check:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content)
    print(json.dumps({"generated_changes": changed, "check": args.check}, separators=(",", ":")))
    return int(args.check and bool(changed))


if __name__ == "__main__":
    raise SystemExit(main())
